-- Supabase Dashboard → SQL Editor でこのファイルの内容を実行してください。
-- （.env.local の DATABASE_URL が Neon など別 DB のとき、CLI からは Supabase に届きません）

create table if not exists public."user-table" (
  "user-id" integer generated by default as identity primary key,
  "user-name" varchar(255) not null,
  "user-pass" varchar(255) not null
);

create table if not exists public."user-report" (
  "report-id" integer generated by default as identity primary key,
  "user-id" integer not null references public."user-table"("user-id") on delete cascade,
  title varchar(255),
  "text" text
);

create index if not exists "user-report_user-id_idx" on public."user-report" ("user-id");
